"""create core tables

Revision ID: 70d869e426eb
Revises: 27890c2c7a9f
Create Date: 2026-02-25 17:53:24.790238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70d869e426eb'
down_revision: Union[str, Sequence[str], None] = '27890c2c7a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('nomenclature', sa.String(length=255), nullable=False),
    sa.Column('ekn_code', sa.String(length=100), nullable=False),
    sa.Column('shift_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number', 'batch_date', name='uq_batch_number_date')
    )
    op.create_index('idx_batch_closed', 'batches', ['is_closed'], unique=False)
    op.create_index('idx_batch_shift_times', 'batches', ['shift_start', 'shift_end'], unique=False)
    op.create_index(op.f('ix_batches_batch_date'), 'batches', ['batch_date'], unique=False)
    op.create_index(op.f('ix_batches_batch_number'), 'batches', ['batch_number'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_code', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('is_aggregated', sa.Boolean(), nullable=False),
    sa.Column('aggregated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_batch_aggregated', 'products', ['batch_id', 'is_aggregated'], unique=False)
    op.create_index(op.f('ix_products_batch_id'), 'products', ['batch_id'], unique=False)
    op.create_index(op.f('ix_products_is_aggregated'), 'products', ['is_aggregated'], unique=False)
    op.create_index(op.f('ix_products_unique_code'), 'products', ['unique_code'], unique=True)
    op.alter_column('work_centers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_centers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_centers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_centers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_products_unique_code'), table_name='products')
    op.drop_index(op.f('ix_products_is_aggregated'), table_name='products')
    op.drop_index(op.f('ix_products_batch_id'), table_name='products')
    op.drop_index('idx_product_batch_aggregated', table_name='products')
    op.drop_table('products')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_date'), table_name='batches')
    op.drop_index('idx_batch_shift_times', table_name='batches')
    op.drop_index('idx_batch_closed', table_name='batches')
    op.drop_table('batches')
    op.drop_table('webhook_subscriptions')
    # ### end Alembic commands ###
